In [33]:
import pandas as pd
import numpy as np

df_ds1 = pd.read_csv("../data/01_raw/anime.csv")
df_ds2 = pd.read_csv("../data/01_raw/MAL-all-from-winter1917-to-fall2022.csv")
df_scraped = pd.read_csv("../data/01_raw/anime_scrapy_consolidated.csv", sep="|")
df_missing = pd.read_csv("../data/01_raw/missing_anime.csv")

In [34]:
df_ds1.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [35]:
df_ds2.head()

,title,MAL_id,type,studio,release-season,release-year,release-date,source-material,genres,themes,demographics,episodes,score,members
0,Dekobou Shingachou: Meian no Shippai,23189,Movie,['Unknown'],winter,1917.0,NaN,Original,['Comedy'],[],NaN,1.0,5.86,1300.0
1,Imokawa Mukuzo: Genkanban no Maki,17387,Movie,['Unknown'],winter,1917.0,NaN,Original,['Comedy'],[],NaN,1.0,5.36,964.0
2,Namakura Gatana,6654,Movie,['Unknown'],spring,1917.0,NaN,Original,['Comedy'],[],NaN,1.0,5.51,8400.0
3,Saru to Kani no Gassen,10742,Movie,['Unknown'],spring,1917.0,NaN,Other,['Drama'],[],NaN,1.0,4.90,953.0
4,Yume no Jidousha,24575,Movie,['Unknown'],spring,1917.0,NaN,Original,[],[],NaN,1.0,0.00,510.0

In [36]:
df_list = [df_ds1, df_ds2, df_scraped, df_missing]

for df in df_list:
    print(df.columns)

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')
Index(['title', 'MAL_id', 'type', 'studio', 'release-season', 'release-year',
       'release-date', 'source-material', 'genres', 'themes', 'demographics',
       'episodes', 'score', 'members'],
      dtype='object')
Index(['anime_id', 'synopsis', 'image_url', 'rating', 'va_list', 'staff_list',
       'recommended_review_count', 'mixedfeelings_review_count',
       'notrecommended_review_count'],
      dtype='object')
Index(['anime_id'], dtype='object')

In [37]:
# Merging kaggle datasets 1 and 2
df_left = df_ds1[['anime_id', 'name', 'type', 'episodes', 'rating', 'members']]
df_right = df_ds2[['MAL_id', 'studio', 'release-season', 'release-year', 'release-date', 'source-material', 'genres', 'themes', 'demographics']]
df = pd.merge(df_left, df_right , how="left", left_on="anime_id", right_on="MAL_id")
df = df.drop(columns="MAL_id")
df.rename(columns={"rating":"mal_score"}, inplace=True)
df.head()

,anime_id,name,type,episodes,mal_score,members,studio,release-season,release-year,release-date,source-material,genres,themes,demographics
0,32281,Kimi no Na wa.,Movie,1,9.37,200630,['CoMix Wave Films'],summer,2016.0,NaN,Original,"['Award Winning', 'Drama', 'Supernatural']",[],NaN
1,5114,Fullmetal Alchemist: Brotherhood,TV,64,9.26,793665,['Bones'],spring,2009.0,NaN,Manga,"['Action', 'Adventure', 'Drama', 'Fantasy']",['Military'],Shounen
2,5114,Fullmetal Alchemist: Brotherhood,TV,64,9.26,793665,['Bones'],summer,2009.0,NaN,Manga,"['Action', 'Adventure', 'Drama', 'Fantasy']",['Military'],Shounen
3,5114,Fullmetal Alchemist: Brotherhood,TV,64,9.26,793665,['Bones'],fall,2009.0,NaN,Manga,"['Action', 'Adventure', 'Drama', 'Fantasy']",['Military'],Shounen
4,5114,Fullmetal Alchemist: Brotherhood,TV,64,9.26,793665,['Bones'],winter,2010.0,NaN,Manga,"['Action', 'Adventure', 'Drama', 'Fantasy']",['Military'],Shounen

In [38]:
# Merging dataset with scraped dataset
df_left = df
df_right = df_scraped
df = pd.merge(df_left, df_right , how="left", on="anime_id")
pd.set_option('display.max_columns', None)
df.head()

,anime_id,name,type,episodes,mal_score,members,studio,release-season,release-year,release-date,source-material,genres,themes,demographics,synopsis,image_url,rating,va_list,staff_list,recommended_review_count,mixedfeelings_review_count,notrecommended_review_count
0,32281,Kimi no Na wa.,Movie,1,9.37,200630,['CoMix Wave Films'],summer,2016.0,NaN,Original,"['Award Winning', 'Drama', 'Supernatural']",[],NaN,"Mitsuha Miyamizu, a high school girl, yearns t...",https://cdn.myanimelist.net/images/anime/5/870...,PG-13 - Teens 13 or older,"['Kamishiraishi, Mone', 'Kamiki, Ryunosuke', '...","['Bezerra, Wendel', 'Kawamura, Genki', 'Itou, ...",808.0,88.0,50.0
1,5114,Fullmetal Alchemist: Brotherhood,TV,64,9.26,793665,['Bones'],spring,2009.0,NaN,Manga,"['Action', 'Adventure', 'Drama', 'Fantasy']",['Military'],Shounen,After a horrific alchemy experiment goes wrong...,https://cdn.myanimelist.net/images/anime/1208/...,R - 17+ (violence & profanity),"['Park, Romi', 'Kugimiya, Rie', 'Miki, Shinich...","['Cook, Justin', 'Maruyama, Hiroo', 'Yonai, No...",912.0,59.0,39.0
2,5114,Fullmetal Alchemist: Brotherhood,TV,64,9.26,793665,['Bones'],summer,2009.0,NaN,Manga,"['Action', 'Adventure', 'Drama', 'Fantasy']",['Military'],Shounen,After a horrific alchemy experiment goes wrong...,https://cdn.myanimelist.net/images/anime/1208/...,R - 17+ (violence & profanity),"['Park, Romi', 'Kugimiya, Rie', 'Miki, Shinich...","['Cook, Justin', 'Maruyama, Hiroo', 'Yonai, No...",912.0,59.0,39.0
3,5114,Fullmetal Alchemist: Brotherhood,TV,64,9.26,793665,['Bones'],fall,2009.0,NaN,Manga,"['Action', 'Adventure', 'Drama', 'Fantasy']",['Military'],Shounen,After a horrific alchemy experiment goes wrong...,https://cdn.myanimelist.net/images/anime/1208/...,R - 17+ (violence & profanity),"['Park, Romi', 'Kugimiya, Rie', 'Miki, Shinich...","['Cook, Justin', 'Maruyama, Hiroo', 'Yonai, No...",912.0,59.0,39.0
4,5114,Fullmetal Alchemist: Brotherhood,TV,64,9.26,793665,['Bones'],winter,2010.0,NaN,Manga,"['Action', 'Adventure', 'Drama', 'Fantasy']",['Military'],Shounen,After a horrific alchemy experiment goes wrong...,https://cdn.myanimelist.net/images/anime/1208/...,R - 17+ (violence & profanity),"['Park, Romi', 'Kugimiya, Rie', 'Miki, Shinich...","['Cook, Justin', 'Maruyama, Hiroo', 'Yonai, No...",912.0,59.0,39.0

In [39]:
# Removing missing anime from dataset and rating
df_final = df
df_final = df_final[~df['anime_id'].isin(df_missing['anime_id'])]
df_final = df_final.drop_duplicates(subset="anime_id", keep="first")
df_final.head()

df_rating = pd.read_csv('../data/01_raw/rating.csv')
df_final_rating = df_rating[~df_rating["anime_id"].isin(df_missing['anime_id'])]

In [41]:
# Exporting dataset to 03_primary
anime_output_path = "../data/03_primary/anime_final.csv"
df_final.to_csv(anime_output_path, sep="|", index=False)

rating_output_path = "../data/03_primary/rating_final.csv"
df_final_rating.to_csv(rating_output_path, sep="|", index=False)